version: '3.8'

services:
  db:
    image: postgres:15
    container_name: music_db
    restart: always
    environment:
      POSTGRES_DB: music
      POSTGRES_USER: av_music_postgres
      POSTGRES_PASSWORD: music123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
